apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

# configMapGenerator:
# - name: cm
#   literals:
#     - foo=2
#   options:
#     disableNameSuffixHash: true

components:
- ../../components/dc

openapi:
  path: openapi.json
